# Generated by Django 4.0 on 2022-01-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=210, null=True)),
                ('email', models.CharField(blank=True, max_length=210, null=True)),
                ('password', models.CharField(blank=True, max_length=210, null=True)),
                ('auth_token', models.CharField(blank=True, max_length=210, null=True)),
            ],
            options={
                'db_table': 'admin_details',
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(blank=True, max_length=210, null=True)),
                ('b_publisher', models.CharField(blank=True, max_length=210, null=True)),
                ('b_type', models.CharField(blank=True, max_length=210, null=True)),
                ('book_token', models.CharField(blank=True, max_length=210, null=True)),
            ],
            options={
                'db_table': 'book_details',
            },
        ),
    ]
