# Generated by Django 4.0 on 2022-01-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_alter_admindetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admindetails',
            name='email',
            field=models.CharField(blank=True, max_length=210, null=True),
        ),
    ]
